CREATE TABLE `gallery`(
`id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
`title` VARCHAR(250) NOT NULL,
`img` VARCHAR(250) NOT NULL,
`cat_id` INT(10) UNSIGNED NULL,
PRIMARY KEY (`id`),
FOREIGN KEY ( `cat_id` ) REFERENCES `_st` ( `id` ) ON DELETE CASCADE,
UNIQUE INDEX `title` ( `title`)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8;

CREATE TABLE `gallery_item`(
`id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
`title` VARCHAR(250) NULL,
`f_content` TEXT NULL,
`img` VARCHAR(250) NOT NULL,
`gallery_id` TINYINT UNSIGNED NULL,
PRIMARY KEY (`id`),
FOREIGN KEY (`gallery_id`) REFERENCES `gallery` (`id`) ON DELETE CASCADE
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8;