/*
CREATE TABLE `partner`(
`id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
`title` VARCHAR(250) NOT NULL,
`url` VARCHAR(250) NOT NULL,
PRIMARY KEY (`id`),
UNIQUE INDEX `title` ( `title`)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8;
*/