CREATE TABLE `_usr`(
`id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
`email` VARCHAR(250) NOT NULL,
`status` ENUM( 'active', 'blocked', 'inactive' ) NOT NULL DEFAULT 'inactive',
`name` VARCHAR(250) NULL DEFAULT NULL,
`surname` VARCHAR(250) NULL DEFAULT NULL,
`hash` VARCHAR(250) NULL DEFAULT NULL,
`tries_left` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
`created` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`last_conn_time` INT(10) UNSIGNED NULL,
`last_login_time` INT(10) UNSIGNED NULL,
`last_ip` VARCHAR(20) NULL DEFAULT NULL,
`pw` VARCHAR(250) NOT NULL,
PRIMARY KEY (`id`),
UNIQUE INDEX `email` ( `email`),
INDEX `status` (`status`),
INDEX `name` (`name`),
INDEX `surname` (`surname`),
INDEX `hash` (`hash`),
INDEX `tries_left` (`tries_left`),
INDEX `created` (`created`),
INDEX `last_conn_time` (`last_conn_time`),
INDEX `last_login_time` (`last_login_time`),
INDEX `last_ip` (`last_ip`)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8;