CREATE TABLE `static`(
`id` TINYINT( 3 ) UNSIGNED NOT NULL AUTO_INCREMENT,
`title` VARCHAR(250) NOT NULL,
`f_content` TEXT NULL,
`active` TINYINT(1) NOT NULL DEFAULT 0,
`cat_id` INT(10) UNSIGNED NULL,
PRIMARY KEY (`id`),
FOREIGN KEY (`cat_id`) REFERENCES `_st` (`id` ) ON DELETE SET NULL,
UNIQUE INDEX `title` ( `title`),
INDEX `active` (`active`)
) ENGINE = INNODB DEFAULT CHARACTER SET = UTF8;